name = "paideia/dao_contracts"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'paideia/dao_contracts'"

[repository]
user = "paideia"
project = "dao_contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"
